/* tslint:disable */
/* eslint-disable */
/**
 * Session-Based Chatty LLM API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessage } from './ChatMessage';
import {
    ChatMessageFromJSON,
    ChatMessageFromJSONTyped,
    ChatMessageToJSON,
    ChatMessageToJSONTyped,
} from './ChatMessage';

/**
 * The response body for fetching messages from a session.
 * @export
 * @interface FetchMessagesResponse
 */
export interface FetchMessagesResponse {
    /**
     * 
     * @type {Array<ChatMessage>}
     * @memberof FetchMessagesResponse
     */
    messages: Array<ChatMessage>;
}

/**
 * Check if a given object implements the FetchMessagesResponse interface.
 */
export function instanceOfFetchMessagesResponse(value: object): value is FetchMessagesResponse {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function FetchMessagesResponseFromJSON(json: any): FetchMessagesResponse {
    return FetchMessagesResponseFromJSONTyped(json, false);
}

export function FetchMessagesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchMessagesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': ((json['messages'] as Array<any>).map(ChatMessageFromJSON)),
    };
}

export function FetchMessagesResponseToJSON(json: any): FetchMessagesResponse {
    return FetchMessagesResponseToJSONTyped(json, false);
}

export function FetchMessagesResponseToJSONTyped(value?: FetchMessagesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': ((value['messages'] as Array<any>).map(ChatMessageToJSON)),
    };
}

